import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { AppState } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { createMnemonic, isValidMnemonic, mnemonicToSeed } from '@shiba-wallet/core';
import type { DerivedAccount } from '@shiba-wallet/core';
import { CHAINS, chainByCaip2 } from './chains';
import {
  bindSecureStore,
  deleteMnemonic,
  deletePublicAccounts,
  dropPhraseTicket,
  loadPublicAccount,
  nativeSecureStoreBackend,
  phraseLocation,
  PROMPTS,
  readPhrase,
  saveNewPhrase,
  savePublicAccount,
  sessionKeyVault,
  upgradePhraseProtectionIfAutomatic,
  type PublicChainEntry,
} from './storage';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { forgetAllSessions } from './sessions';
import { addAaSentListener } from './aa';
import { recoveryRecordListener, wipeRecoveryData } from './recovery';
import { resetPasskeys } from './passkeys';
import {
  MAX_ACCOUNTS,
  addAccount as addAccountToStore,
  defaultAccountsState,
  deriveChainAccounts,
  deriveSignerFor,
  hideAccount as hideAccountInStore,
  loadAccounts,
  renameAccount as renameAccountInStore,
  resetAccounts,
  setActiveAccount,
  unhideAccount as unhideAccountInStore,
  type AccountsState,
  type ChainAccount,
} from './accounts';

export type { ChainAccount } from './accounts';

// The one place the native secure-store module is handed to ./storage.ts,
// which owns every read and write of key material (see its header). Done at
// module load so the vault exists before any screen (e.g. the Sessions
// screen's sessionKeyVault) can use it.
bindSecureStore(nativeSecureStoreBackend(SecureStore));

export type WalletStatus = 'loading' | 'no-wallet' | 'ready';

/** One account of the wallet as the UI lists it (public data only). */
export interface AccountView {
  /** Derivation index (docs/ARCHITECTURE.md ADR D8). */
  index: number;
  name: string;
  hidden: boolean;
  /** The account's EVM address (m/44'/60'/0'/0/index), or null if not derived. */
  evmAddress: string | null;
}

interface WalletContextValue {
  status: WalletStatus;
  /**
   * The ACTIVE account's addresses on the launch chains; empty until
   * status is 'ready'. Every screen reads its addresses from here, so an
   * account switch re-targets balances, receive, send, activity, swap
   * and WalletConnect at once.
   */
  accounts: ChainAccount[];
  /** The active account; null until status is 'ready'. */
  activeAccount: AccountView | null;
  /** Every account, ascending by index, hidden ones included. */
  accountList: AccountView[];
  /** The account whose EVM address this is (case-insensitive), or null. */
  accountForEvmAddress: (address: string) => AccountView | null;
  /** Makes a visible account the active one (persisted). */
  switchAccount: (index: number) => Promise<void>;
  /** Creates the next account (never reusing an index); does not switch. */
  addAccount: (name?: string | null) => Promise<AccountView>;
  renameAccount: (index: number, name: string) => Promise<void>;
  /** Hides a non-active account other than the first; keys are unaffected. */
  hideAccount: (index: number) => Promise<void>;
  unhideAccount: (index: number) => Promise<void>;
  /**
   * Mnemonic generated by beginCreate and not yet persisted. Held only in
   * memory while the user completes the backup flow.
   */
  pendingMnemonic: string | null;
  /** Generates a fresh mnemonic for the create-wallet flow (not persisted yet). */
  beginCreate: () => void;
  /** Discards a pending mnemonic without persisting it. */
  cancelCreate: () => void;
  /** Persists the pending mnemonic after the backup quiz and unlocks the wallet. */
  confirmCreate: () => Promise<void>;
  /** Validates and persists a user-supplied mnemonic, then unlocks the wallet. */
  importExisting: (mnemonic: string) => Promise<void>;
  /** Reads the mnemonic back from secure storage (Settings reveal). */
  revealMnemonic: () => Promise<string | null>;
  /**
   * Re-derives the ACTIVE account's signing key for one chain and hands it
   * to fn for the duration of one signing operation. `expectAddress` is
   * the address the operation was prepared for (the confirm screen's
   * "From"): if the active account's key does not control exactly that
   * address — e.g. the account was switched after the quote — nothing is
   * signed and the call throws. Keys are never kept resident: the seed is
   * zeroed before this resolves, and the DerivedAccount (whose sign
   * closure captures the private key) must not be stored by callers.
   */
  signWith: <T>(
    chainId: string,
    expectAddress: string,
    fn: (account: DerivedAccount) => Promise<T>,
  ) => Promise<T>;
  /** Deletes the mnemonic from secure storage and resets to onboarding. */
  wipe: () => Promise<void>;
}

const WalletContext = createContext<WalletContextValue | null>(null);

/**
 * Derives the public data (addresses, paths) of the given accounts on
 * every launch chain from the mnemonic, through the single mapping in
 * ./accounts.ts. The 64-byte seed is zeroed before returning and the
 * DerivedAccount objects (which capture private keys in their sign
 * closures) are dropped inside deriveChainAccounts; only addresses and
 * paths leave this function. Signing re-derives on demand (signWith).
 */
function derivePublic(mnemonic: string, indices: number[]): Record<number, ChainAccount[]> {
  const seed = mnemonicToSeed(mnemonic);
  try {
    const out: Record<number, ChainAccount[]> = {};
    for (const index of indices) out[index] = deriveChainAccounts(seed, index);
    return out;
  } finally {
    seed.fill(0);
  }
}

const EVM_SLOT = 'eip155:1';

/** Public data for the secure-storage account cache (no key material). */
function toPublicEntries(accounts: ChainAccount[]): PublicChainEntry[] {
  return accounts.map(({ chainId, address, path }) => ({ chainId, address, path }));
}

/**
 * Rebuilds ChainAccount rows from cached public entries, in launch-chain
 * order with the current display metadata. null unless every launch chain
 * is present (an incomplete entry is re-derived instead of half-shown).
 */
function hydratePublic(entries: PublicChainEntry[] | null): ChainAccount[] | null {
  if (!entries) return null;
  const out: ChainAccount[] = [];
  for (const { provider, symbol, accent } of CHAINS) {
    const entry = entries.find((e) => e.chainId === provider.chainId);
    if (!entry) return null;
    out.push({
      chainId: provider.chainId,
      name: provider.name,
      symbol,
      accent,
      address: entry.address,
      path: entry.path,
    });
  }
  return out;
}

/** Best-effort write of the public cache; a failure only costs a later re-derivation. */
async function cachePublic(derived: Record<number, ChainAccount[]>): Promise<void> {
  for (const [index, accounts] of Object.entries(derived)) {
    await savePublicAccount(Number(index), toPublicEntries(accounts)).catch(() => undefined);
  }
}

/** Every index the cache can hold (accounts are hidden, never deleted, so indices stay below MAX_ACCOUNTS). */
const ALL_CACHE_INDICES = Array.from({ length: MAX_ACCOUNTS }, (_, i) => i);

const PROMPT_LOAD_ACCOUNTS = 'Unlock Shiba Wallet to show your accounts';
const PROMPT_NEW_ACCOUNT = 'Unlock your recovery phrase to create the account';

export function WalletProvider({ children }: { children: React.ReactNode }) {
  const [status, setStatus] = useState<WalletStatus>('loading');
  const [accountsState, setAccountsState] = useState<AccountsState | null>(null);
  // Public data only (see derivePublic); keyed by account index.
  const [derived, setDerived] = useState<Record<number, ChainAccount[]>>({});
  const [pendingMnemonic, setPendingMnemonic] = useState<string | null>(null);

  // signWith reads the active index through a ref so a signing call made
  // after a switch can never use a stale closure's index.
  const activeIndexRef = useRef(0);
  const commitAccounts = useCallback((state: AccountsState | null) => {
    activeIndexRef.current = state?.activeIndex ?? 0;
    setAccountsState(state);
  }, []);

  // Account-store mutations run one at a time (rapid taps must not lose
  // updates between the store's read and write).
  const queue = useRef<Promise<unknown>>(Promise.resolve());
  const serialized = useCallback(<T,>(task: () => Promise<T>): Promise<T> => {
    const run = queue.current.then(task, task);
    queue.current = run.catch(() => undefined);
    return run;
  }, []);

  // Recovery records (phase 8 item 4): a Kernel v3.3 account's record is
  // started on its first accepted smart-account operation, whichever screen
  // sent it (aa.ts notifies after the bundler accepted; public data only).
  useEffect(() => addAaSentListener(recoveryRecordListener(AsyncStorage)), []);

  // A phrase held by the approval gate (./storage.ts) never outlives the
  // app's time in the foreground. Only 'background' counts: iOS reports
  // 'inactive' while its own Face ID prompt is up, and dropping the phrase
  // that prompt just opened would only cause a second prompt.
  useEffect(() => {
    const sub = AppState.addEventListener('change', (next) => {
      if (next === 'background') dropPhraseTicket();
    });
    return () => sub.remove();
  }, []);

  // On launch, check secure storage for an existing wallet.
  //  - Standard storage: read the phrase (no prompt) and derive, as before.
  //  - Protected storage: draw the accounts from the public cache, so the
  //    app starts without a biometric prompt; only an account missing from
  //    the cache needs the phrase (one system prompt).
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const location = await phraseLocation();
        if (cancelled) return;
        if (location === 'none') {
          setStatus('no-wallet');
          return;
        }
        if (location === 'standard') {
          const mnemonic = await readPhrase(PROMPT_LOAD_ACCOUNTS);
          if (cancelled) return;
          if (!mnemonic || !isValidMnemonic(mnemonic)) {
            setStatus('no-wallet');
            return;
          }
          const state = await loadAccounts();
          if (cancelled) return;
          const fresh = derivePublic(mnemonic, state.accounts.map((a) => a.index));
          setDerived(fresh);
          commitAccounts(state);
          setStatus('ready');
          void cachePublic(fresh);
          return;
        }
        const state = await loadAccounts();
        if (cancelled) return;
        const fromCache: Record<number, ChainAccount[]> = {};
        const missing: number[] = [];
        for (const { index } of state.accounts) {
          const rows = hydratePublic(await loadPublicAccount(index));
          if (rows) fromCache[index] = rows;
          else missing.push(index);
        }
        if (missing.length > 0) {
          // Rare (the cache is written whenever addresses are derived). If
          // the prompt is cancelled or the phrase cannot be opened, the
          // wallet still opens with the cached accounts; a missing one is
          // derived again when it is next switched to.
          try {
            const mnemonic = await readPhrase(PROMPT_LOAD_ACCOUNTS);
            if (mnemonic && isValidMnemonic(mnemonic)) {
              const fresh = derivePublic(mnemonic, missing);
              Object.assign(fromCache, fresh);
              void cachePublic(fresh);
            }
          } catch {
            // Shown later: signing reports why the phrase cannot be opened.
          }
        }
        if (cancelled) return;
        setDerived(fromCache);
        commitAccounts(state);
        setStatus('ready');
      } catch {
        // Secure storage unavailable (e.g. locked device edge case): fall
        // back to onboarding rather than crash. Nothing is deleted.
        if (!cancelled) setStatus('no-wallet');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [commitAccounts]);

  const beginCreate = useCallback(() => {
    // 128 bits = 12 words. Entropy comes from crypto.getRandomValues via the
    // expo-crypto polyfill installed in src/polyfills.ts.
    setPendingMnemonic(createMnemonic(128));
  }, []);

  const cancelCreate = useCallback(() => {
    setPendingMnemonic(null);
  }, []);

  const activate = useCallback(
    async (mnemonic: string) => {
      // Standard storage first, then (policy 'automatic') the move into
      // biometric-protected storage: the two-step order means a cancelled
      // or refused protection prompt can never cost the phrase. Android
      // shows two system prompts here (protected write + read-back check),
      // iOS one (the read-back). Any outcome other than success leaves the
      // wallet working from standard storage, and Settings shows why.
      await saveNewPhrase(mnemonic);
      // A cache left by a previous wallet must never label this one.
      await deletePublicAccounts(ALL_CACHE_INDICES);
      const fresh = derivePublic(mnemonic, [0]);
      await cachePublic(fresh);
      await upgradePhraseProtectionIfAutomatic();
      // A new or imported wallet starts with the default list (Account 1 =
      // index 0). Further accounts of an imported phrase reappear with
      // their original keys when added again, because indices are handed
      // out in order.
      const state = await resetAccounts().catch(() => defaultAccountsState());
      setDerived(fresh);
      commitAccounts(state);
      setPendingMnemonic(null);
      setStatus('ready');
    },
    [commitAccounts],
  );

  const confirmCreate = useCallback(async () => {
    if (!pendingMnemonic) {
      throw new Error('No wallet creation in progress');
    }
    await activate(pendingMnemonic);
  }, [pendingMnemonic, activate]);

  const importExisting = useCallback(
    async (raw: string) => {
      const mnemonic = raw.trim().toLowerCase().split(/\s+/).join(' ');
      if (!isValidMnemonic(mnemonic)) {
        throw new Error('Invalid BIP-39 mnemonic (bad word or checksum)');
      }
      await activate(mnemonic);
    },
    [activate],
  );

  // Uses the phrase the Settings approval prompt just opened (no second
  // prompt). Returns null when it cannot be opened (cancelled, or the
  // protected copy became unreadable — Settings' storage-protection row
  // then explains the latter).
  const revealMnemonic = useCallback(async () => {
    try {
      return await readPhrase('Reveal recovery phrase');
    } catch {
      return null;
    }
  }, []);

  // Mirror of `derived` for the async account actions below. It is updated
  // after every commit (refs must not be written while rendering); a layout
  // effect runs before any passive effect or later event can read it.
  // ensureDerived also writes it directly so a caller sees fresh entries
  // before the state update has rendered.
  const derivedRef = useRef(derived);
  useLayoutEffect(() => {
    derivedRef.current = derived;
  });

  /** Derives public data for indices not derived yet (e.g. after an add). */
  const ensureDerived = useCallback(async (indices: number[]) => {
    let missing = indices.filter((i) => derivedRef.current[i] === undefined);
    if (missing.length === 0) return;
    // The public cache first (no prompt), then the phrase for the rest.
    const cached: Record<number, ChainAccount[]> = {};
    for (const index of missing) {
      const rows = hydratePublic(await loadPublicAccount(index));
      if (rows) cached[index] = rows;
    }
    missing = missing.filter((i) => cached[i] === undefined);
    let fresh: Record<number, ChainAccount[]> = {};
    if (missing.length > 0) {
      const mnemonic = await readPhrase(PROMPT_NEW_ACCOUNT);
      if (!mnemonic) throw new Error('No wallet found in secure storage');
      fresh = derivePublic(mnemonic, missing);
      await cachePublic(fresh);
    }
    Object.assign(fresh, cached);
    setDerived((prev) => ({ ...prev, ...fresh }));
    derivedRef.current = { ...derivedRef.current, ...fresh };
  }, []);
  const switchAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        await ensureDerived([index]);
        commitAccounts(await setActiveAccount(index));
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const addAccount = useCallback(
    (name: string | null = null) =>
      serialized(async () => {
        const { state, account } = await addAccountToStore(name);
        await ensureDerived([account.index]);
        commitAccounts(state);
        const evmAddress =
          derivedRef.current[account.index]?.find((c) => c.chainId === EVM_SLOT)?.address ?? null;
        return { ...account, evmAddress };
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const renameAccount = useCallback(
    (index: number, name: string) =>
      serialized(async () => {
        commitAccounts(await renameAccountInStore(index, name));
      }),
    [serialized, commitAccounts],
  );

  const hideAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        commitAccounts(await hideAccountInStore(index));
      }),
    [serialized, commitAccounts],
  );

  const unhideAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        await ensureDerived([index]);
        commitAccounts(await unhideAccountInStore(index));
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const signWith = useCallback(
    async <T,>(
      chainId: string,
      expectAddress: string,
      fn: (account: DerivedAccount) => Promise<T>,
    ): Promise<T> => {
      const chain = chainByCaip2(chainId);
      if (!chain) throw new Error(`Unknown chain ${chainId}`);
      const index = activeIndexRef.current;
      // The phrase the approval prompt just opened, or (protected storage,
      // nothing held) one system prompt. Throws PhraseAccessError with a
      // plain-language message when it cannot be opened.
      const mnemonic = await readPhrase(PROMPTS.signFallback);
      if (!mnemonic) throw new Error('No wallet found in secure storage');
      const seed = mnemonicToSeed(mnemonic);
      try {
        // The active account's key, and only if it controls exactly the
        // address the operation was prepared for (see ./accounts.ts).
        const account = deriveSignerFor(chain.provider, seed, index, expectAddress);
        return await fn(account);
      } finally {
        seed.fill(0);
      }
    },
    [],
  );

  const wipe = useCallback(async () => {
    // Session keys (phase 8 item 2) are key material too: delete them from
    // secure storage with the list (best-effort; on-chain grants are not
    // affected — the Sessions screen warns about that before a wipe).
    await forgetAllSessions(AsyncStorage, sessionKeyVault).catch(() => undefined);
    // Recovery records, recoveries in progress and recovered-account
    // attachments are local bookkeeping (no key material); they go with the
    // wallet. Nothing on-chain changes. Settings offers the record export
    // before this runs.
    await wipeRecoveryData(AsyncStorage).catch(() => undefined);
    // Passkey details (phase 8 item 3) are public metadata only (the private
    // key lives in the platform authenticator); they go with the wallet. An
    // installed passkey stays installed on-chain — Settings says so.
    await resetPasskeys(AsyncStorage).catch(() => undefined);
    await deleteMnemonic();
    // The public account cache (addresses only) goes with the wallet.
    await deletePublicAccounts(ALL_CACHE_INDICES);
    await resetAccounts().catch(() => undefined);
    setDerived({});
    commitAccounts(null);
    setPendingMnemonic(null);
    setStatus('no-wallet');
  }, [commitAccounts]);

  const accountList = useMemo<AccountView[]>(
    () =>
      (accountsState?.accounts ?? []).map((a) => ({
        ...a,
        evmAddress: derived[a.index]?.find((c) => c.chainId === EVM_SLOT)?.address ?? null,
      })),
    [accountsState, derived],
  );

  const activeIndex = accountsState?.activeIndex ?? 0;
  const activeAccount = useMemo(
    () => (accountsState ? (accountList.find((a) => a.index === activeIndex) ?? null) : null),
    [accountsState, accountList, activeIndex],
  );
  const accounts = useMemo(() => derived[activeIndex] ?? [], [derived, activeIndex]);

  const accountForEvmAddress = useCallback(
    (address: string) => {
      const lower = address.toLowerCase();
      return accountList.find((a) => a.evmAddress?.toLowerCase() === lower) ?? null;
    },
    [accountList],
  );

  const value = useMemo<WalletContextValue>(
    () => ({
      status,
      accounts,
      activeAccount,
      accountList,
      accountForEvmAddress,
      switchAccount,
      addAccount,
      renameAccount,
      hideAccount,
      unhideAccount,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    }),
    [
      status,
      accounts,
      activeAccount,
      accountList,
      accountForEvmAddress,
      switchAccount,
      addAccount,
      renameAccount,
      hideAccount,
      unhideAccount,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    ],
  );

  return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>;
}

export function useWallet(): WalletContextValue {
  const ctx = useContext(WalletContext);
  if (!ctx) throw new Error('useWallet must be used inside WalletProvider');
  return ctx;
}
