import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { createMnemonic, isValidMnemonic, mnemonicToSeed } from '@shiba-wallet/core';
import type { DerivedAccount } from '@shiba-wallet/core';
import { chainByCaip2 } from './chains';
import { deleteMnemonic, loadMnemonic, saveMnemonic, sessionKeyVault } from './storage';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { forgetAllSessions } from './sessions';
import { addAaSentListener } from './aa';
import { recoveryRecordListener, wipeRecoveryData } from './recovery';
import { resetPasskeys } from './passkeys';
import {
  addAccount as addAccountToStore,
  defaultAccountsState,
  deriveChainAccounts,
  deriveSignerFor,
  hideAccount as hideAccountInStore,
  loadAccounts,
  renameAccount as renameAccountInStore,
  resetAccounts,
  setActiveAccount,
  unhideAccount as unhideAccountInStore,
  type AccountsState,
  type ChainAccount,
} from './accounts';

export type { ChainAccount } from './accounts';

export type WalletStatus = 'loading' | 'no-wallet' | 'ready';

/** One account of the wallet as the UI lists it (public data only). */
export interface AccountView {
  /** Derivation index (docs/ARCHITECTURE.md ADR D8). */
  index: number;
  name: string;
  hidden: boolean;
  /** The account's EVM address (m/44'/60'/0'/0/index), or null if not derived. */
  evmAddress: string | null;
}

interface WalletContextValue {
  status: WalletStatus;
  /**
   * The ACTIVE account's addresses on the launch chains; empty until
   * status is 'ready'. Every screen reads its addresses from here, so an
   * account switch re-targets balances, receive, send, activity, swap
   * and WalletConnect at once.
   */
  accounts: ChainAccount[];
  /** The active account; null until status is 'ready'. */
  activeAccount: AccountView | null;
  /** Every account, ascending by index, hidden ones included. */
  accountList: AccountView[];
  /** The account whose EVM address this is (case-insensitive), or null. */
  accountForEvmAddress: (address: string) => AccountView | null;
  /** Makes a visible account the active one (persisted). */
  switchAccount: (index: number) => Promise<void>;
  /** Creates the next account (never reusing an index); does not switch. */
  addAccount: (name?: string | null) => Promise<AccountView>;
  renameAccount: (index: number, name: string) => Promise<void>;
  /** Hides a non-active account other than the first; keys are unaffected. */
  hideAccount: (index: number) => Promise<void>;
  unhideAccount: (index: number) => Promise<void>;
  /**
   * Mnemonic generated by beginCreate and not yet persisted. Held only in
   * memory while the user completes the backup flow.
   */
  pendingMnemonic: string | null;
  /** Generates a fresh mnemonic for the create-wallet flow (not persisted yet). */
  beginCreate: () => void;
  /** Discards a pending mnemonic without persisting it. */
  cancelCreate: () => void;
  /** Persists the pending mnemonic after the backup quiz and unlocks the wallet. */
  confirmCreate: () => Promise<void>;
  /** Validates and persists a user-supplied mnemonic, then unlocks the wallet. */
  importExisting: (mnemonic: string) => Promise<void>;
  /** Reads the mnemonic back from secure storage (Settings reveal). */
  revealMnemonic: () => Promise<string | null>;
  /**
   * Re-derives the ACTIVE account's signing key for one chain and hands it
   * to fn for the duration of one signing operation. `expectAddress` is
   * the address the operation was prepared for (the confirm screen's
   * "From"): if the active account's key does not control exactly that
   * address — e.g. the account was switched after the quote — nothing is
   * signed and the call throws. Keys are never kept resident: the seed is
   * zeroed before this resolves, and the DerivedAccount (whose sign
   * closure captures the private key) must not be stored by callers.
   */
  signWith: <T>(
    chainId: string,
    expectAddress: string,
    fn: (account: DerivedAccount) => Promise<T>,
  ) => Promise<T>;
  /** Deletes the mnemonic from secure storage and resets to onboarding. */
  wipe: () => Promise<void>;
}

const WalletContext = createContext<WalletContextValue | null>(null);

/**
 * Derives the public data (addresses, paths) of the given accounts on
 * every launch chain from the mnemonic, through the single mapping in
 * ./accounts.ts. The 64-byte seed is zeroed before returning and the
 * DerivedAccount objects (which capture private keys in their sign
 * closures) are dropped inside deriveChainAccounts; only addresses and
 * paths leave this function. Signing re-derives on demand (signWith).
 */
function derivePublic(mnemonic: string, indices: number[]): Record<number, ChainAccount[]> {
  const seed = mnemonicToSeed(mnemonic);
  try {
    const out: Record<number, ChainAccount[]> = {};
    for (const index of indices) out[index] = deriveChainAccounts(seed, index);
    return out;
  } finally {
    seed.fill(0);
  }
}

const EVM_SLOT = 'eip155:1';

export function WalletProvider({ children }: { children: React.ReactNode }) {
  const [status, setStatus] = useState<WalletStatus>('loading');
  const [accountsState, setAccountsState] = useState<AccountsState | null>(null);
  // Public data only (see derivePublic); keyed by account index.
  const [derived, setDerived] = useState<Record<number, ChainAccount[]>>({});
  const [pendingMnemonic, setPendingMnemonic] = useState<string | null>(null);

  // signWith reads the active index through a ref so a signing call made
  // after a switch can never use a stale closure's index.
  const activeIndexRef = useRef(0);
  const commitAccounts = useCallback((state: AccountsState | null) => {
    activeIndexRef.current = state?.activeIndex ?? 0;
    setAccountsState(state);
  }, []);

  // Account-store mutations run one at a time (rapid taps must not lose
  // updates between the store's read and write).
  const queue = useRef<Promise<unknown>>(Promise.resolve());
  const serialized = useCallback(<T,>(task: () => Promise<T>): Promise<T> => {
    const run = queue.current.then(task, task);
    queue.current = run.catch(() => undefined);
    return run;
  }, []);

  // Recovery records (phase 8 item 4): a Kernel v3.3 account's record is
  // started on its first accepted smart-account operation, whichever screen
  // sent it (aa.ts notifies after the bundler accepted; public data only).
  useEffect(() => addAaSentListener(recoveryRecordListener(AsyncStorage)), []);

  // On launch, check secure storage for an existing wallet.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const mnemonic = await loadMnemonic();
        if (cancelled) return;
        if (mnemonic && isValidMnemonic(mnemonic)) {
          const state = await loadAccounts();
          if (cancelled) return;
          setDerived(derivePublic(mnemonic, state.accounts.map((a) => a.index)));
          commitAccounts(state);
          setStatus('ready');
        } else {
          setStatus('no-wallet');
        }
      } catch {
        // Secure storage unavailable (e.g. locked device edge case): fall
        // back to onboarding rather than crash. Nothing is deleted.
        if (!cancelled) setStatus('no-wallet');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [commitAccounts]);

  const beginCreate = useCallback(() => {
    // 128 bits = 12 words. Entropy comes from crypto.getRandomValues via the
    // expo-crypto polyfill installed in src/polyfills.ts.
    setPendingMnemonic(createMnemonic(128));
  }, []);

  const cancelCreate = useCallback(() => {
    setPendingMnemonic(null);
  }, []);

  const activate = useCallback(
    async (mnemonic: string) => {
      await saveMnemonic(mnemonic);
      // A new or imported wallet starts with the default list (Account 1 =
      // index 0). Further accounts of an imported phrase reappear with
      // their original keys when added again, because indices are handed
      // out in order.
      const state = await resetAccounts().catch(() => defaultAccountsState());
      setDerived(derivePublic(mnemonic, [0]));
      commitAccounts(state);
      setPendingMnemonic(null);
      setStatus('ready');
    },
    [commitAccounts],
  );

  const confirmCreate = useCallback(async () => {
    if (!pendingMnemonic) {
      throw new Error('No wallet creation in progress');
    }
    await activate(pendingMnemonic);
  }, [pendingMnemonic, activate]);

  const importExisting = useCallback(
    async (raw: string) => {
      const mnemonic = raw.trim().toLowerCase().split(/\s+/).join(' ');
      if (!isValidMnemonic(mnemonic)) {
        throw new Error('Invalid BIP-39 mnemonic (bad word or checksum)');
      }
      await activate(mnemonic);
    },
    [activate],
  );

  const revealMnemonic = useCallback(() => loadMnemonic(), []);

  const derivedRef = useRef(derived);
  derivedRef.current = derived;

  /** Derives public data for indices not derived yet (e.g. after an add). */
  const ensureDerived = useCallback(async (indices: number[]) => {
    const missing = indices.filter((i) => derivedRef.current[i] === undefined);
    if (missing.length === 0) return;
    const mnemonic = await loadMnemonic();
    if (!mnemonic) throw new Error('No wallet found in secure storage');
    const fresh = derivePublic(mnemonic, missing);
    setDerived((prev) => ({ ...prev, ...fresh }));
    derivedRef.current = { ...derivedRef.current, ...fresh };
  }, []);
  const switchAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        await ensureDerived([index]);
        commitAccounts(await setActiveAccount(index));
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const addAccount = useCallback(
    (name: string | null = null) =>
      serialized(async () => {
        const { state, account } = await addAccountToStore(name);
        await ensureDerived([account.index]);
        commitAccounts(state);
        const evmAddress =
          derivedRef.current[account.index]?.find((c) => c.chainId === EVM_SLOT)?.address ?? null;
        return { ...account, evmAddress };
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const renameAccount = useCallback(
    (index: number, name: string) =>
      serialized(async () => {
        commitAccounts(await renameAccountInStore(index, name));
      }),
    [serialized, commitAccounts],
  );

  const hideAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        commitAccounts(await hideAccountInStore(index));
      }),
    [serialized, commitAccounts],
  );

  const unhideAccount = useCallback(
    (index: number) =>
      serialized(async () => {
        await ensureDerived([index]);
        commitAccounts(await unhideAccountInStore(index));
      }),
    [serialized, ensureDerived, commitAccounts],
  );

  const signWith = useCallback(
    async <T,>(
      chainId: string,
      expectAddress: string,
      fn: (account: DerivedAccount) => Promise<T>,
    ): Promise<T> => {
      const chain = chainByCaip2(chainId);
      if (!chain) throw new Error(`Unknown chain ${chainId}`);
      const index = activeIndexRef.current;
      const mnemonic = await loadMnemonic();
      if (!mnemonic) throw new Error('No wallet found in secure storage');
      const seed = mnemonicToSeed(mnemonic);
      try {
        // The active account's key, and only if it controls exactly the
        // address the operation was prepared for (see ./accounts.ts).
        const account = deriveSignerFor(chain.provider, seed, index, expectAddress);
        return await fn(account);
      } finally {
        seed.fill(0);
      }
    },
    [],
  );

  const wipe = useCallback(async () => {
    // Session keys (phase 8 item 2) are key material too: delete them from
    // secure storage with the list (best-effort; on-chain grants are not
    // affected — the Sessions screen warns about that before a wipe).
    await forgetAllSessions(AsyncStorage, sessionKeyVault).catch(() => undefined);
    // Recovery records, recoveries in progress and recovered-account
    // attachments are local bookkeeping (no key material); they go with the
    // wallet. Nothing on-chain changes. Settings offers the record export
    // before this runs.
    await wipeRecoveryData(AsyncStorage).catch(() => undefined);
    // Passkey details (phase 8 item 3) are public metadata only (the private
    // key lives in the platform authenticator); they go with the wallet. An
    // installed passkey stays installed on-chain — Settings says so.
    await resetPasskeys(AsyncStorage).catch(() => undefined);
    await deleteMnemonic();
    await resetAccounts().catch(() => undefined);
    setDerived({});
    commitAccounts(null);
    setPendingMnemonic(null);
    setStatus('no-wallet');
  }, [commitAccounts]);

  const accountList = useMemo<AccountView[]>(
    () =>
      (accountsState?.accounts ?? []).map((a) => ({
        ...a,
        evmAddress: derived[a.index]?.find((c) => c.chainId === EVM_SLOT)?.address ?? null,
      })),
    [accountsState, derived],
  );

  const activeIndex = accountsState?.activeIndex ?? 0;
  const activeAccount = useMemo(
    () => (accountsState ? (accountList.find((a) => a.index === activeIndex) ?? null) : null),
    [accountsState, accountList, activeIndex],
  );
  const accounts = useMemo(() => derived[activeIndex] ?? [], [derived, activeIndex]);

  const accountForEvmAddress = useCallback(
    (address: string) => {
      const lower = address.toLowerCase();
      return accountList.find((a) => a.evmAddress?.toLowerCase() === lower) ?? null;
    },
    [accountList],
  );

  const value = useMemo<WalletContextValue>(
    () => ({
      status,
      accounts,
      activeAccount,
      accountList,
      accountForEvmAddress,
      switchAccount,
      addAccount,
      renameAccount,
      hideAccount,
      unhideAccount,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    }),
    [
      status,
      accounts,
      activeAccount,
      accountList,
      accountForEvmAddress,
      switchAccount,
      addAccount,
      renameAccount,
      hideAccount,
      unhideAccount,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    ],
  );

  return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>;
}

export function useWallet(): WalletContextValue {
  const ctx = useContext(WalletContext);
  if (!ctx) throw new Error('useWallet must be used inside WalletProvider');
  return ctx;
}
