import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';
import { createMnemonic, isValidMnemonic, mnemonicToSeed } from '@shiba-wallet/core';
import type { DerivedAccount } from '@shiba-wallet/core';
import { CHAINS, chainByCaip2 } from './chains';
import { deleteMnemonic, loadMnemonic, saveMnemonic } from './storage';

/** One derived account-0 address for one chain, safe to keep in app state. */
export interface ChainAccount {
  chainId: string;
  name: string;
  symbol: string;
  accent: string;
  address: string;
  path: string;
}

export type WalletStatus = 'loading' | 'no-wallet' | 'ready';

interface WalletContextValue {
  status: WalletStatus;
  /** Account-0 addresses for the launch chains; empty until status is 'ready'. */
  accounts: ChainAccount[];
  /**
   * Mnemonic generated by beginCreate and not yet persisted. Held only in
   * memory while the user completes the backup flow.
   */
  pendingMnemonic: string | null;
  /** Generates a fresh mnemonic for the create-wallet flow (not persisted yet). */
  beginCreate: () => void;
  /** Discards a pending mnemonic without persisting it. */
  cancelCreate: () => void;
  /** Persists the pending mnemonic after the backup quiz and unlocks the wallet. */
  confirmCreate: () => Promise<void>;
  /** Validates and persists a user-supplied mnemonic, then unlocks the wallet. */
  importExisting: (mnemonic: string) => Promise<void>;
  /** Reads the mnemonic back from secure storage (Settings reveal). */
  revealMnemonic: () => Promise<string | null>;
  /**
   * Re-derives the account-0 signing key for one chain and hands it to fn
   * for the duration of one signing operation. Keys are never kept
   * resident: the seed is zeroed before this resolves, and the
   * DerivedAccount (whose sign closure captures the private key) must not
   * be stored by callers — use it and drop it.
   */
  signWith: <T>(chainId: string, fn: (account: DerivedAccount) => Promise<T>) => Promise<T>;
  /** Deletes the mnemonic from secure storage and resets to onboarding. */
  wipe: () => Promise<void>;
}

const WalletContext = createContext<WalletContextValue | null>(null);

/**
 * Derives the account-0 address of every launch chain from the mnemonic.
 * Only public data (addresses, paths) leaves this function; the 64-byte seed
 * is zeroed before returning, and the DerivedAccount objects (which capture
 * private keys in their sign closures) are dropped. Signing flows in later
 * phases will re-derive on demand instead of keeping keys resident.
 */
function deriveAccounts(mnemonic: string): ChainAccount[] {
  const seed = mnemonicToSeed(mnemonic);
  try {
    return CHAINS.map(({ provider, symbol, accent }) => {
      const account = provider.deriveAccount(seed, 0, 0);
      return {
        chainId: provider.chainId,
        name: provider.name,
        symbol,
        accent,
        address: account.address,
        path: account.path,
      };
    });
  } finally {
    seed.fill(0);
  }
}

export function WalletProvider({ children }: { children: React.ReactNode }) {
  const [status, setStatus] = useState<WalletStatus>('loading');
  const [accounts, setAccounts] = useState<ChainAccount[]>([]);
  const [pendingMnemonic, setPendingMnemonic] = useState<string | null>(null);

  // On launch, check secure storage for an existing wallet.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const mnemonic = await loadMnemonic();
        if (cancelled) return;
        if (mnemonic && isValidMnemonic(mnemonic)) {
          setAccounts(deriveAccounts(mnemonic));
          setStatus('ready');
        } else {
          setStatus('no-wallet');
        }
      } catch {
        // Secure storage unavailable (e.g. locked device edge case): fall
        // back to onboarding rather than crash. Nothing is deleted.
        if (!cancelled) setStatus('no-wallet');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const beginCreate = useCallback(() => {
    // 128 bits = 12 words. Entropy comes from crypto.getRandomValues via the
    // expo-crypto polyfill installed in src/polyfills.ts.
    setPendingMnemonic(createMnemonic(128));
  }, []);

  const cancelCreate = useCallback(() => {
    setPendingMnemonic(null);
  }, []);

  const activate = useCallback(async (mnemonic: string) => {
    await saveMnemonic(mnemonic);
    setAccounts(deriveAccounts(mnemonic));
    setPendingMnemonic(null);
    setStatus('ready');
  }, []);

  const confirmCreate = useCallback(async () => {
    if (!pendingMnemonic) {
      throw new Error('No wallet creation in progress');
    }
    await activate(pendingMnemonic);
  }, [pendingMnemonic, activate]);

  const importExisting = useCallback(
    async (raw: string) => {
      const mnemonic = raw.trim().toLowerCase().split(/\s+/).join(' ');
      if (!isValidMnemonic(mnemonic)) {
        throw new Error('Invalid BIP-39 mnemonic (bad word or checksum)');
      }
      await activate(mnemonic);
    },
    [activate],
  );

  const revealMnemonic = useCallback(() => loadMnemonic(), []);

  const signWith = useCallback(
    async <T,>(chainId: string, fn: (account: DerivedAccount) => Promise<T>): Promise<T> => {
      const chain = chainByCaip2(chainId);
      if (!chain) throw new Error(`Unknown chain ${chainId}`);
      const mnemonic = await loadMnemonic();
      if (!mnemonic) throw new Error('No wallet found in secure storage');
      const seed = mnemonicToSeed(mnemonic);
      try {
        // Same account/index the rest of the app displays (account 0).
        const account = chain.provider.deriveAccount(seed, 0, 0);
        return await fn(account);
      } finally {
        seed.fill(0);
      }
    },
    [],
  );

  const wipe = useCallback(async () => {
    await deleteMnemonic();
    setAccounts([]);
    setPendingMnemonic(null);
    setStatus('no-wallet');
  }, []);

  const value = useMemo<WalletContextValue>(
    () => ({
      status,
      accounts,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    }),
    [
      status,
      accounts,
      pendingMnemonic,
      beginCreate,
      cancelCreate,
      confirmCreate,
      importExisting,
      revealMnemonic,
      signWith,
      wipe,
    ],
  );

  return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>;
}

export function useWallet(): WalletContextValue {
  const ctx = useContext(WalletContext);
  if (!ctx) throw new Error('useWallet must be used inside WalletProvider');
  return ctx;
}
